version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: "edge"
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  eventservice.client:
    restart: always
    build:
      context: .\..\src\EventPlatform
      dockerfile: EventService.Client/Dockerfile
    ports:
      - 80:80
    depends_on:
      eventservice.server:
        condition: service_started
  
  eventservice.server:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConStr-MongoDB: mongodb://root:example@mongo-db:27017/
    build:
      context: .\..\src\EventPlatform
      dockerfile: EventService.Server/Dockerfile
    depends_on:
      mongo-db:
        condition: service_started
      keycloak:
        condition: service_healthy