version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [
        'start-dev'
      ]
    ports:
      - 5001:8080

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  
  eventservice.client:
    restart: always
    build:
      context: .\..\src\EventPlatform
      dockerfile: EventService.Client/Dockerfile
    ports:
      - 5101:80
  
  eventservice.server:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      identityUrl: http://identity-api
      ConStr-MongoDB: mongodb://root:example@mongo-db:27017/
    expose:
      - "80"
    ports:
      - "5102:80"
    build:
      context: .\..\src\EventPlatform
      dockerfile: EventService.Server/Dockerfile
    depends_on:
      - mongo-db